# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/qubeck/Documents/Development/ProjektyVHDL/Zynq7020CoreBoard/tangerineNX_Z7/tangerineNX_Z7.srcs/sources_1/ip/gfxFbRam/gfxFbRam.xci
# IP: The module: 'gfxFbRam' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/Zynq7020CoreBoard/tangerineNX_Z7/tangerineNX_Z7.gen/sources_1/ip/gfxFbRam/gfxFbRam_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gfxFbRam'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/qubeck/Documents/Development/ProjektyVHDL/Zynq7020CoreBoard/tangerineNX_Z7/tangerineNX_Z7.srcs/sources_1/ip/gfxFbRam/gfxFbRam.xci
# IP: The module: 'gfxFbRam' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/Zynq7020CoreBoard/tangerineNX_Z7/tangerineNX_Z7.gen/sources_1/ip/gfxFbRam/gfxFbRam_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gfxFbRam'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
