# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/tangerineNX_Z7.xdc

# Block Designs: bd/tangerineNX_Z7/tangerineNX_Z7.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tangerineNX_Z7 || ORIG_REF_NAME==tangerineNX_Z7} -quiet] -quiet

# IP: bd/tangerineNX_Z7/ip/tangerineNX_Z7_processing_system7_0_0/tangerineNX_Z7_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tangerineNX_Z7_processing_system7_0_0 || ORIG_REF_NAME==tangerineNX_Z7_processing_system7_0_0} -quiet] -quiet

# IP: bd/tangerineNX_Z7/ip/tangerineNX_Z7_proc_sys_reset_0_0/tangerineNX_Z7_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tangerineNX_Z7_proc_sys_reset_0_0 || ORIG_REF_NAME==tangerineNX_Z7_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/tangerineNX_Z7/ip/tangerineNX_Z7_xbar_0/tangerineNX_Z7_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tangerineNX_Z7_xbar_0 || ORIG_REF_NAME==tangerineNX_Z7_xbar_0} -quiet] -quiet

# IP: bd/tangerineNX_Z7/ip/tangerineNX_Z7_axi_interconnect_0_0/tangerineNX_Z7_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tangerineNX_Z7_axi_interconnect_0_0 || ORIG_REF_NAME==tangerineNX_Z7_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/tangerineNX_Z7/ip/tangerineNX_Z7_axi_bram_ctrl_0_0/tangerineNX_Z7_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tangerineNX_Z7_axi_bram_ctrl_0_0 || ORIG_REF_NAME==tangerineNX_Z7_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/tangerineNX_Z7/ip/tangerineNX_Z7_blk_mem_gen_0_0/tangerineNX_Z7_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tangerineNX_Z7_blk_mem_gen_0_0 || ORIG_REF_NAME==tangerineNX_Z7_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/tangerineNX_Z7/ip/tangerineNX_Z7_clk_wiz_0_0/tangerineNX_Z7_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tangerineNX_Z7_clk_wiz_0_0 || ORIG_REF_NAME==tangerineNX_Z7_clk_wiz_0_0} -quiet] -quiet

# IP: bd/tangerineNX_Z7/ip/tangerineNX_Z7_hdmiOut_0_0/tangerineNX_Z7_hdmiOut_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tangerineNX_Z7_hdmiOut_0_0 || ORIG_REF_NAME==tangerineNX_Z7_hdmiOut_0_0} -quiet] -quiet

# IP: bd/tangerineNX_Z7/ip/tangerineNX_Z7_vga_0_0/tangerineNX_Z7_vga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tangerineNX_Z7_vga_0_0 || ORIG_REF_NAME==tangerineNX_Z7_vga_0_0} -quiet] -quiet

# IP: ip/fontPROM/fontPROM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fontPROM || ORIG_REF_NAME==fontPROM} -quiet] -quiet

# IP: bd/tangerineNX_Z7/ip/tangerineNX_Z7_ps2Host_0_0/tangerineNX_Z7_ps2Host_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tangerineNX_Z7_ps2Host_0_0 || ORIG_REF_NAME==tangerineNX_Z7_ps2Host_0_0} -quiet] -quiet

# IP: ip/ps2ControllerFifo/ps2ControllerFifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ps2ControllerFifo || ORIG_REF_NAME==ps2ControllerFifo} -quiet] -quiet

# IP: bd/tangerineNX_Z7/ip/tangerineNX_Z7_axi_interconnect_1_0/tangerineNX_Z7_axi_interconnect_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tangerineNX_Z7_axi_interconnect_1_0 || ORIG_REF_NAME==tangerineNX_Z7_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/tangerineNX_Z7/ip/tangerineNX_Z7_vgaDMA_0_0/tangerineNX_Z7_vgaDMA_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tangerineNX_Z7_vgaDMA_0_0 || ORIG_REF_NAME==tangerineNX_Z7_vgaDMA_0_0} -quiet] -quiet

# IP: ip/gfxFbRam/gfxFbRam.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gfxFbRam || ORIG_REF_NAME==gfxFbRam} -quiet] -quiet

# IP: bd/tangerineNX_Z7/ip/tangerineNX_Z7_rootRegs_0_0/tangerineNX_Z7_rootRegs_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tangerineNX_Z7_rootRegs_0_0 || ORIG_REF_NAME==tangerineNX_Z7_rootRegs_0_0} -quiet] -quiet

# IP: bd/tangerineNX_Z7/ip/tangerineNX_Z7_is2Controller_0_0/tangerineNX_Z7_is2Controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tangerineNX_Z7_is2Controller_0_0 || ORIG_REF_NAME==tangerineNX_Z7_is2Controller_0_0} -quiet] -quiet

# IP: ip/i2sControllerFifo/i2sControllerFifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2sControllerFifo || ORIG_REF_NAME==i2sControllerFifo} -quiet] -quiet

# IP: bd/tangerineNX_Z7/ip/tangerineNX_Z7_auto_pc_5/tangerineNX_Z7_auto_pc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tangerineNX_Z7_auto_pc_5 || ORIG_REF_NAME==tangerineNX_Z7_auto_pc_5} -quiet] -quiet

# IP: bd/tangerineNX_Z7/ip/tangerineNX_Z7_auto_pc_0/tangerineNX_Z7_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tangerineNX_Z7_auto_pc_0 || ORIG_REF_NAME==tangerineNX_Z7_auto_pc_0} -quiet] -quiet

# IP: bd/tangerineNX_Z7/ip/tangerineNX_Z7_auto_pc_1/tangerineNX_Z7_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tangerineNX_Z7_auto_pc_1 || ORIG_REF_NAME==tangerineNX_Z7_auto_pc_1} -quiet] -quiet

# IP: bd/tangerineNX_Z7/ip/tangerineNX_Z7_auto_pc_2/tangerineNX_Z7_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tangerineNX_Z7_auto_pc_2 || ORIG_REF_NAME==tangerineNX_Z7_auto_pc_2} -quiet] -quiet

# IP: bd/tangerineNX_Z7/ip/tangerineNX_Z7_auto_pc_3/tangerineNX_Z7_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tangerineNX_Z7_auto_pc_3 || ORIG_REF_NAME==tangerineNX_Z7_auto_pc_3} -quiet] -quiet

# IP: bd/tangerineNX_Z7/ip/tangerineNX_Z7_auto_pc_4/tangerineNX_Z7_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tangerineNX_Z7_auto_pc_4 || ORIG_REF_NAME==tangerineNX_Z7_auto_pc_4} -quiet] -quiet

# IP: bd/tangerineNX_Z7/ip/tangerineNX_Z7_auto_pc_6/tangerineNX_Z7_auto_pc_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tangerineNX_Z7_auto_pc_6 || ORIG_REF_NAME==tangerineNX_Z7_auto_pc_6} -quiet] -quiet

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/Zynq7020CoreBoard/tangerineNX_Z7/tangerineNX_Z7.gen/sources_1/bd/tangerineNX_Z7/ip/tangerineNX_Z7_processing_system7_0_0/tangerineNX_Z7_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tangerineNX_Z7_processing_system7_0_0 || ORIG_REF_NAME==tangerineNX_Z7_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/Zynq7020CoreBoard/tangerineNX_Z7/tangerineNX_Z7.gen/sources_1/bd/tangerineNX_Z7/ip/tangerineNX_Z7_proc_sys_reset_0_0/tangerineNX_Z7_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tangerineNX_Z7_proc_sys_reset_0_0 || ORIG_REF_NAME==tangerineNX_Z7_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/Zynq7020CoreBoard/tangerineNX_Z7/tangerineNX_Z7.gen/sources_1/bd/tangerineNX_Z7/ip/tangerineNX_Z7_proc_sys_reset_0_0/tangerineNX_Z7_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tangerineNX_Z7_proc_sys_reset_0_0 || ORIG_REF_NAME==tangerineNX_Z7_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/Zynq7020CoreBoard/tangerineNX_Z7/tangerineNX_Z7.gen/sources_1/bd/tangerineNX_Z7/ip/tangerineNX_Z7_blk_mem_gen_0_0/tangerineNX_Z7_blk_mem_gen_0_0_ooc.xdc

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/Zynq7020CoreBoard/tangerineNX_Z7/tangerineNX_Z7.gen/sources_1/bd/tangerineNX_Z7/ip/tangerineNX_Z7_clk_wiz_0_0/tangerineNX_Z7_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tangerineNX_Z7_clk_wiz_0_0 || ORIG_REF_NAME==tangerineNX_Z7_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/Zynq7020CoreBoard/tangerineNX_Z7/tangerineNX_Z7.gen/sources_1/bd/tangerineNX_Z7/ip/tangerineNX_Z7_clk_wiz_0_0/tangerineNX_Z7_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tangerineNX_Z7_clk_wiz_0_0 || ORIG_REF_NAME==tangerineNX_Z7_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/Zynq7020CoreBoard/tangerineNX_Z7/tangerineNX_Z7.gen/sources_1/bd/tangerineNX_Z7/ip/tangerineNX_Z7_clk_wiz_0_0/tangerineNX_Z7_clk_wiz_0_0_ooc.xdc

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/Zynq7020CoreBoard/tangerineNX_Z7/tangerineNX_Z7.gen/sources_1/bd/tangerineNX_Z7/ip/tangerineNX_Z7_auto_pc_5/tangerineNX_Z7_auto_pc_5_ooc.xdc

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/Zynq7020CoreBoard/tangerineNX_Z7/tangerineNX_Z7.gen/sources_1/bd/tangerineNX_Z7/ip/tangerineNX_Z7_auto_pc_0/tangerineNX_Z7_auto_pc_0_ooc.xdc

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/Zynq7020CoreBoard/tangerineNX_Z7/tangerineNX_Z7.gen/sources_1/bd/tangerineNX_Z7/ip/tangerineNX_Z7_auto_pc_1/tangerineNX_Z7_auto_pc_1_ooc.xdc

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/Zynq7020CoreBoard/tangerineNX_Z7/tangerineNX_Z7.gen/sources_1/bd/tangerineNX_Z7/ip/tangerineNX_Z7_auto_pc_2/tangerineNX_Z7_auto_pc_2_ooc.xdc

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/Zynq7020CoreBoard/tangerineNX_Z7/tangerineNX_Z7.gen/sources_1/bd/tangerineNX_Z7/ip/tangerineNX_Z7_auto_pc_3/tangerineNX_Z7_auto_pc_3_ooc.xdc

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/Zynq7020CoreBoard/tangerineNX_Z7/tangerineNX_Z7.gen/sources_1/bd/tangerineNX_Z7/ip/tangerineNX_Z7_auto_pc_4/tangerineNX_Z7_auto_pc_4_ooc.xdc

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/Zynq7020CoreBoard/tangerineNX_Z7/tangerineNX_Z7.gen/sources_1/bd/tangerineNX_Z7/ip/tangerineNX_Z7_auto_pc_6/tangerineNX_Z7_auto_pc_6_ooc.xdc

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/Zynq7020CoreBoard/tangerineNX_Z7/tangerineNX_Z7.gen/sources_1/bd/tangerineNX_Z7/tangerineNX_Z7_ooc.xdc
